spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/webflux_demo
    mongo:
      repositories:
        enabled: true
  main:
    allow-bean-definition-overriding: true

  security:
    oauth2:
      client:
        clientId: 989431064515-jvqh2n3mr861fel4uvqdouppcjco4n4g.apps.googleusercontent.com
        clientSecret: rRvQCfQWeMhMnAxQF0ZGuGM1
        accessTokenUri: https://www.googleapis.com/oauth2/v3/token
        userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
        tokenName: oauth_token
        authenticationScheme: query
        clientAuthenticationScheme: form
        scope: profile
      resource:
        userInfoUri: https://www.googleapis.com/userinfo/v2/me
        preferTokenInfo: false